version: "3"
services:
  smahub:
    build: .
    container_name: smahub
    network_mode: "host"
    restart: unless-stopped
    environment:
      -  TRIPOWERX_ENABLED=true
      -  TRIPOWERX_ADDRESS=192.168.0.1
      -  TRIPOWERX_USER=user
      -  TRIPOWERX_PASSWORD=pwd
      -  MQTT_ENABLED=true
      -  MQTT_ADDRESS=192.168.0.2
      -  MQTT_PORT=1883