version: "3"
services:
  smahub:
    build: .
    container_name: smahub
    network_mode: "host"
    restart: unless-stopped
    # forward python debug server port - not necessary with network_mode: "host"
    #    ports:
    #      - 5678:5678
    environment:
      - TRIPOWERX_ENABLED=true
      - TRIPOWERX_ADDRESS=192.0.2.1
      - TRIPOWERX_USER=user
      - TRIPOWERX_PASSWORD=pwd
      - MQTT_ENABLED=true
      - MQTT_ADDRESS=192.0.2.2
      - MQTT_PORT=1883
      - SHM2_ENABLED=true
