'''
Home Assistant MQTT autodiscovery sensor definitions for SMA devices
'''

SENSORS_TRIPOWERX = [
    # device info
    {
        'key': "device_info.name",
        'name': "Device name",
        'entity_category': "diagnostic",
        'icon': "mdi:border-all",
    },
    {
        'key': "device_info.identifiers",
        'name': "Device serial",
        'entity_category': "diagnostic",
        'icon': "mdi:border-all",
    },
    {
        'key': "device_info.model",
        'name': "Device model",
        'entity_category': "diagnostic",
        'icon': "mdi:border-all",
    },
    {
        'key': "device_info.manufacturer",
        'name': "Device manufacturer",
        'entity_category': "diagnostic",
        'icon': "mdi:border-all",
    },
    {
        'key': "device_info.sw_version",
        'name': "Device SW version",
        'entity_category': "diagnostic",
        'icon': "mdi:border-all",
    },
    # global measurements
    {
        'key': "Coolsys.Inverter.TmpVal",
        'name': "Inverter temperature [3]",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'device_class': "temperature",
        'unit_of_measurement': "°C",
        'icon': "mdi:thermometer",
    },
    {
        'key': "DcMs.Amp",
        'name': "DC current input [C]",
        'state_class': "total_increasing",
        'suggested_display_precision': 2,
        'device_class': "current",
        'unit_of_measurement': "A",
        'icon': "mdi:current-dc",
    },
    {
        'key': "DcMs.Vol",
        'name': "DC voltage input [C]",
        'suggested_display_precision': 2,
        'device_class': "voltage",
        'unit_of_measurement': "V",
        'icon': "mdi:flash-triangle-outline",
    },
    {
        'key': "DcMs.Watt",
        'name': "DC power input [C]",
        'suggested_display_precision': 2,
        'unit_of_measurement': "W",
        'device_class': "power",
        'state_class': "measurement",
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "GridGuard.Cntry",
        'name': "Country standard set",
        'suggested_display_precision': 2,
    },
    {
        'device_class': "current",
        'icon': "mdi:current-ac",
        'key': "GridMs.A.phsA",
        'name': "Grid current phase L1",
        'state_class': "total_increasing",
        'suggested_display_precision': 2,
        'unit_of_measurement': "A",
    },
    {
        'device_class': "current",
        'icon': "mdi:current-ac",
        'key': "GridMs.A.phsB",
        'name': "Grid current phase L2",
        'state_class': "total_increasing",
        'suggested_display_precision': 2,
        'unit_of_measurement': "A",
    },
    {
        'device_class': "current",
        'icon': "mdi:current-ac",
        'key': "GridMs.A.phsC",
        'name': "Grid current phase L3",
        'state_class': "total_increasing",
        'suggested_display_precision': 2,
        'unit_of_measurement': "A",
    },
    {
        'key': "GridMs.Hz",
        'name': "Grid frequency",
        'suggested_display_precision': 2,
        'unit_of_measurement': "Hz",
        'device_class': "frequency",
        'state_class': "measurement",
        'icon': "mdi:sine-wave",
    },
    {
        'key': "GridMs.PhV.phsA",
        'name': "Grid voltage phase L1",
        'suggested_display_precision': 2,
        'device_class': "voltage",
        'unit_of_measurement': "V",
        'icon': "mdi:flash-triangle-outline",
    },
    {
        'key': "GridMs.PhV.phsA2B",
        'name': "Grid voltage phase L1 against L2",
        'suggested_display_precision': 2,
        'device_class': "voltage",
        'unit_of_measurement': "V",
        'icon': "mdi:flash-triangle-outline",
    },
    {
        'key': "GridMs.PhV.phsB",
        'name': "Grid voltage phase L2",
        'suggested_display_precision': 2,
        'device_class': "voltage",
        'unit_of_measurement': "V",
        'icon': "mdi:flash-triangle-outline",
    },
    {
        'key': "GridMs.PhV.phsB2C",
        'name': "Grid voltage phase L2 against L3",
        'suggested_display_precision': 2,
        'device_class': "voltage",
        'unit_of_measurement': "V",
        'icon': "mdi:flash-triangle-outline",
    },
    {
        'key': "GridMs.PhV.phsC",
        'name': "Grid voltage phase L3",
        'suggested_display_precision': 2,
        'device_class': "voltage",
        'unit_of_measurement': "V",
        'icon': "mdi:flash-triangle-outline",
    },
    {
        'key': "GridMs.PhV.phsC2A",
        'name': "Grid voltage phase L3 against L1",
        'suggested_display_precision': 2,
        'device_class': "voltage",
        'unit_of_measurement': "V",
        'icon': "mdi:flash-triangle-outline",
    },
    {
        'device_class': "current",
        'icon': "mdi:current-ac",
        'key': "GridMs.TotA",
        'name': "Grid current",
        'state_class': "total_increasing",
        'suggested_display_precision': 2,
        'unit_of_measurement': "A",
    },
    {
        'key': "GridMs.TotPFEEI",
        'name': "EEI displacement power factor",
        'suggested_display_precision': 2,
    },
    {
        'key': "GridMs.TotPFExt",
        'name': "Excitation type of cos φ",
        'suggested_display_precision': 2,
    },
    {
        'key': "GridMs.TotPFPrc",
        'name': "Displacement power factor",
        'suggested_display_precision': 2,
    },
    {
        'key': "GridMs.TotVA",
        'name': "Apparent power",
        'suggested_display_precision': 2,
        'unit_of_measurement': "VA",
        'device_class': "apparent_power",
        'state_class': "measurement",
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "GridMs.TotVAr",
        'name': "Reactive power",
        'suggested_display_precision': 2,
        'unit_of_measurement': "VAR",
        'device_class': "reactive_power",
        'state_class': "measurement",
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "GridMs.TotW",
        'name': "Power",
        'suggested_display_precision': 2,
        'unit_of_measurement': "W",
        'device_class': "power",
        'state_class': "measurement",
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "GridMs.TotW.Pv",
        'name': "Power",
        'suggested_display_precision': 2,
        'unit_of_measurement': "W",
        'device_class': "power",
        'state_class': "measurement",
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "GridMs.VA.phsA",
        'name': "Apparent power L1",
        'suggested_display_precision': 2,
        'unit_of_measurement': "VA",
        'device_class': "apparent_power",
        'state_class': "measurement",
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "GridMs.VA.phsB",
        'name': "Apparent power L2",
        'suggested_display_precision': 2,
        'unit_of_measurement': "VA",
        'device_class': "apparent_power",
        'state_class': "measurement",
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "GridMs.VA.phsC",
        'name': "Apparent power L3",
        'suggested_display_precision': 2,
        'unit_of_measurement': "VA",
        'device_class': "apparent_power",
        'state_class': "measurement",
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "GridMs.VAr.phsA",
        'name': "Reactive power L1",
        'suggested_display_precision': 2,
        'unit_of_measurement': "VAR",
        'device_class': "reactive_power",
        'state_class': "measurement",
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "GridMs.VAr.phsB",
        'name': "Reactive power L2",
        'suggested_display_precision': 2,
        'unit_of_measurement': "VAR",
        'device_class': "reactive_power",
        'state_class': "measurement",
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "GridMs.VAr.phsC",
        'name': "Reactive power L3",
        'suggested_display_precision': 2,
        'unit_of_measurement': "VAR",
        'device_class': "reactive_power",
        'state_class': "measurement",
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "GridMs.W.phsA",
        'name': "Power L1",
        'suggested_display_precision': 2,
        'unit_of_measurement': "W",
        'device_class': "power",
        'state_class': "measurement",
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "GridMs.W.phsB",
        'name': "Power L2",
        'suggested_display_precision': 2,
        'unit_of_measurement': "W",
        'device_class': "power",
        'state_class': "measurement",
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "GridMs.W.phsC",
        'name': "Power L3",
        'suggested_display_precision': 2,
        'unit_of_measurement': "W",
        'device_class': "power",
        'state_class': "measurement",
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "InOut.GI1",
        'name': "Digital group input",
        'suggested_display_precision': 2,
    },
    {
        'key': "Inverter.VArModCfg.PFCtlVolCfg.Stt",
        'name': "cos φ(V), status",
        'suggested_display_precision': 2,
    },
    {
        'device_class': "current",
        'icon': "mdi:current-dc",
        'key': "Isolation.FltA",
        'name': "Residual current",
        'state_class': "total_increasing",
        'suggested_display_precision': 2,
        'unit_of_measurement': "A",
    },
    {
        'key': "Isolation.LeakRis",
        'name': "Insulation resistance",
        'suggested_display_precision': 2,
        'unit_of_measurement': "kOhm",
    },
    {
        'key': "Metering.TotFeedTms",
        'name': "Feed-in time",
        'suggested_display_precision': 2,
        'unit_of_measurement': "s",
    },
    {
        'key': "Metering.TotOpTms",
        'name': "Operating time",
        'suggested_display_precision': 2,
        'unit_of_measurement': "s",
    },
    {
        'key': "Metering.TotWhOut",
        'name': "Total yield",
        'suggested_display_precision': 2,
        'unit_of_measurement': "kWh",
        'device_class': "energy",
        'state_class': "total_increasing",
        'icon': "mdi:counter",
    },
    {
        'key': "Metering.TotWhOut.Pv",
        'name': "Total yield",
        'suggested_display_precision': 2,
        'unit_of_measurement': "kWh",
        'device_class': "energy",
        'state_class': "total_increasing",
        'icon': "mdi:counter",
    },
    {
        'key': "Operation.BckStt",
        'name': "Backup mode status",
        'suggested_display_precision': 2,
    },
    {
        'key': "Operation.DrtStt",
        'name': "Reason for derating",
        'suggested_display_precision': 2,
    },
    {
        'key': "Operation.Evt.Dsc",
        'name': "Fault correction measure",
        'suggested_display_precision': 2,
    },
    {
        'key': "Operation.Evt.Msg",
        'name': "Message",
        'suggested_display_precision': 2,
    },
    {
        'key': "Operation.EvtCntIstl",
        'name': "Number of events for installer",
        'suggested_display_precision': 2,
    },
    {
        'key': "Operation.EvtCntUsr",
        'name': "Number of events for user",
        'suggested_display_precision': 2,
    },
    {
        'key': "Operation.GriSwCnt",
        'name': "Number of grid connections",
        'suggested_display_precision': 2,
    },
    {
        'key': "Operation.GriSwStt",
        'name': "Grid relay/contactor",
        'suggested_display_precision': 2,
    },
    {
        'key': "Operation.Health",
        'name': "Condition",
        'suggested_display_precision': 2,
    },
    {
        'key': "Operation.HealthStt.Alm",
        'name': "Nominal power in Fault Mode",
        'suggested_display_precision': 2,
        'unit_of_measurement': "W",
        'device_class': "power",
        'state_class': "measurement",
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "Operation.HealthStt.Ok",
        'name': "Nominal power in Ok Mode",
        'suggested_display_precision': 2,
        'unit_of_measurement': "kW",
    },
    {
        'key': "Operation.HealthStt.Wrn",
        'name': "Nominal power in Warning Mode",
        'suggested_display_precision': 2,
        'unit_of_measurement': "W",
        'device_class': "power",
        'state_class': "measurement",
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "Operation.OpStt",
        'name': "General operating status",
        'suggested_display_precision': 2,
    },
    {
        'key': "Operation.PvGriConn",
        'name': "Plant mains connection",
        'suggested_display_precision': 2,
    },
    {
        'key': "Operation.RstrLokStt",
        'name': "Block status",
        'suggested_display_precision': 2,
    },
    {
        'key': "Operation.RunStt",
        'name': "Operating status",
        'suggested_display_precision': 2,
    },
    {
        'key': "Operation.StandbyStt",
        'name': "Standby status",
        'suggested_display_precision': 2,
    },
    {
        'key': "Operation.VArCtl.VArModAct",
        'name': "Active reactive power range",
        'suggested_display_precision': 2,
    },
    {
        'key': "Operation.VArCtl.VArModStt",
        'name': "Active reactive power behavior",
        'suggested_display_precision': 2,
    },
    {
        'key': "Operation.WMaxLimSrc",
        'name': "Source of maximum active power setpoint",
        'suggested_display_precision': 2,
    },
    {
        'key': "Operation.WMinLimSrc",
        'name': "Source of minimum active power setpoint",
        'suggested_display_precision': 2,
    },
    {
        'key': "PvGen.PvW",
        'name': "PV generation power",
        'suggested_display_precision': 2,
        'unit_of_measurement': "W",
        'device_class': "power",
        'state_class': "measurement",
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "PvGen.PvWh",
        'name': "Meter count and PV gen. meter",
        'suggested_display_precision': 2,
        'unit_of_measurement': "kWh",
        'device_class': "energy",
        'state_class': "total_increasing",
        'icon': "mdi:counter",
    },
    {
        'key': "SunSpecSig.SunSpecTx",
        'name': "SunSpec life sign",
        'suggested_display_precision': 2,
    },
    {
        'key': "Upd.Stt",
        'name': "Status of the firmware update",
        'suggested_display_precision': 2,
    },
    {
        'key': "WebConn.Stt",
        'name': "Status of the Webconnect functionality",
        'suggested_display_precision': 2,
    },
    {
        'key': "Wl.ConnStt",
        'name': "Wi-Fi connection status",
        'suggested_display_precision': 2,
    },
    {
        'key': "Wl.SigPwr",
        'name': "Signal strength of the selected network",
        'suggested_display_precision': 2,
        'unit_of_measurement': "%",
    },
    {
        'key': "Setpoint.PlantControl.InOut.DigOut",
        'name': "Digital output",
        'suggested_display_precision': 2,
    },
    {
        'key': "Setpoint.PlantControl.Inverter.WModCfg.WCtlComCfg.W",
        'name': "Active power limitation by PV system control",
        'suggested_display_precision': 2,
        'unit_of_measurement': "W",
        'device_class': "power",
        'state_class': "measurement",
        'icon': "mdi:home-lightning-bolt-outline",
    },
]


SENSORS_SHM2 = [
    # device info
    {
        'key': "device_info.name",
        'name': "Device name",
        'entity_category': "diagnostic",
        'icon': "mdi:camera-switch",
    },
    {
        'key': "device_info.identifiers",
        'name': "Device serial",
        'entity_category': "diagnostic",
        'icon': "mdi:camera-switch",
    },
    {
        'key': "device_info.model",
        'name': "Device model",
        'entity_category': "diagnostic",
        'icon': "mdi:camera-switch",
    },
    {
        'key': "device_info.manufacturer",
        'name': "Device manufacturer",
        'entity_category': "diagnostic",
        'icon': "mdi:camera-switch",
    },
    {
        'key': "device_info.sw_version",
        'name': "Device SW version",
        'entity_category': "diagnostic",
        'icon': "mdi:camera-switch",
    },
    # global measurements
    {
        'key': "p.pconsume",
        'name': "Active power consumption",
        'device_class': "power",
        'unit_of_measurement': "W",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "p.pconsumecounter",
        'name': "Active power consumption counter",
        'device_class': "energy",
        'unit_of_measurement': "kWh",
        'state_class': "total_increasing",
        'suggested_display_precision': 2,
        'icon': "mdi:counter",
    },
    {
        'key': "p.psupply",
        'name': "Active power supply",
        'device_class': "power",
        'unit_of_measurement': "W",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "p.psupplycounter",
        'name': "Active power supply counter",
        'device_class': "energy",
        'unit_of_measurement': "kWh",
        'state_class': "total_increasing",
        'suggested_display_precision': 2,
        'icon': "mdi:counter",
    },
    {
        'key': "q.qconsume",
        'name': "Reactive power consumption",
        'device_class': "reactive_power",
        'unit_of_measurement': "VAR",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "q.qconsumecounter",
        'name': "Reactive power consumption counter",
        'device_class': "energy",
        'unit_of_measurement': "kVAh",
        'suggested_display_precision': 2,
        'icon': "mdi:counter",
    },
    {
        'key': "q.qsupply",
        'name': "Reactive power supply",
        'device_class': "reactive_power",
        'unit_of_measurement': "VAR",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "q.qsupplycounter",
        'name': "Reactive power supply counter",
        'device_class': "energy",
        'unit_of_measurement': "kVAh",
        'state_class': "total_increasing",
        'suggested_display_precision': 2,
        'icon': "mdi:counter",
    },
    {
        'key': "s.sconsume",
        'name': "Apparent power consumption",
        'device_class': "apparent_power",
        'unit_of_measurement': "VA",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "s.sconsumecounter",
        'name': "Apparent power consumption counter",
        'device_class': "energy",
        'unit_of_measurement': "kVAh",
        'state_class': "total_increasing",
        'suggested_display_precision': 2,
        'icon': "mdi:counter",
    },
    {
        'key': "s.ssupply",
        'name': "Apparent power supply",
        'device_class': "apparent_power",
        'unit_of_measurement': "VA",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "s.ssupplycounter",
        'name': "Apparent power supply counter",
        'device_class': "energy",
        'unit_of_measurement': "kVAh",
        'state_class': "total_increasing",
        'suggested_display_precision': 2,
        'icon': "mdi:counter",
    },
    {
        'key': "cosphi",
        'name': "Phase angle cosine",
        'unit_of_measurement': "°",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:cosine-wave",
    },
    {
        'key': "frequency",
        'name': "Grid frequency",
        'device_class': "frequency",
        'unit_of_measurement': "Hz",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:sine-wave",
    },
    # phase 1 measurements
    {
        'key': "p.1.p1consume",
        'name': "Phase 1 consumption",
        'device_class': "power",
        'unit_of_measurement': "W",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "p.1.p1consumecounter",
        'name': "Phase 1 consumption counter",
        'device_class': "energy",
        'unit_of_measurement': "kWh",
        'state_class': "total_increasing",
        'suggested_display_precision': 2,
        'icon': "mdi:counter",
    },
    {
        'key': "p.1.p1supply",
        'name': "Phase 1 active power supply",
        'device_class': "power",
        'unit_of_measurement': "W",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "p.1.p1supplycounter",
        'name': "Phase 1 supply counter",
        'device_class': "energy",
        'unit_of_measurement': "kWh",
        'state_class': "total_increasing",
        'suggested_display_precision': 2,
        'icon': "mdi:counter",
    },
    {
        'key': "q.1.q1consume",
        'name': "Phase 1 reactive power consumption",
        'device_class': "reactive_power",
        'unit_of_measurement': "VAR",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "q.1.q1consumecounter",
        'name': "Phase 1 reactive power consumption counter",
        'device_class': "energy",
        'unit_of_measurement': "kVAh",
        'state_class': "total_increasing",
        'suggested_display_precision': 2,
        'icon': "mdi:counter",
    },
    {
        'key': "q.1.q1supply",
        'name': "Phase 1 reactive power supply",
        'device_class': "reactive_power",
        'unit_of_measurement': "VAR",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "q.1.q1supplycounter",
        'name': "Phase 1 reactive power supply counter",
        'device_class': "energy",
        'unit_of_measurement': "kVAh",
        'state_class': "total_increasing",
        'suggested_display_precision': 2,
        'icon': "mdi:counter",
    },
    {
        'key': "s.1.s1consume",
        'name': "Phase 1 apparent power consumption",
        'device_class': "apparent_power",
        'unit_of_measurement': "VA",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "s.1.s1consumecounter",
        'name': "Phase 1 apparent power consumption counter",
        'device_class': "energy",
        'unit_of_measurement': "kVAh",
        'state_class': "total_increasing",
        'suggested_display_precision': 2,
        'icon': "mdi:counter",
    },
    {
        'key': "s.1.s1supply",
        'name': "Phase 1 apparent power supply",
        'device_class': "apparent_power",
        'unit_of_measurement': "VA",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "s.1.s1supplycounter",
        'name': "Phase 1 apparent power supply counter",
        'device_class': "energy",
        'unit_of_measurement': "kVAh",
        'state_class': "total_increasing",
        'suggested_display_precision': 2,
        'icon': "mdi:counter",
    },
    {
        'key': "1.i1",
        'name': "Phase 1 current",
        'device_class': "current",
        'unit_of_measurement': "A",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:current-ac",
    },
    {
        'key': "1.u1",
        'name': "Phase 1 potential",
        'device_class': "voltage",
        'unit_of_measurement': "V",
        'icon': "mdi:flash-triangle-outline",
        'state_class': "measurement",
        'suggested_display_precision': 2,
    },
    {
        'key': "1.cosphi1",
        'name': "Phase 1 angle cosine",
        'unit_of_measurement': "°",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:cosine-wave",
    },
    # phase 2 measurements
    {
        'key': "p.2.p2consume",
        'name': "Phase 2 consumption",
        'device_class': "power",
        'unit_of_measurement': "W",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "p.2.p2consumecounter",
        'name': "Phase 2 consumption counter",
        'device_class': "energy",
        'unit_of_measurement': "kWh",
        'state_class': "total_increasing",
        'suggested_display_precision': 2,
        'icon': "mdi:counter",
    },
    {
        'key': "p.2.p2supply",
        'name': "Phase 2 active power supply",
        'device_class': "power",
        'unit_of_measurement': "W",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "p.2.p2supplycounter",
        'name': "Phase 2 supply counter",
        'device_class': "energy",
        'unit_of_measurement': "kWh",
        'state_class': "total_increasing",
        'suggested_display_precision': 2,
        'icon': "mdi:counter",
    },
    {
        'key': "q.2.q2consume",
        'name': "Phase 2 reactive power consumption",
        'device_class': "reactive_power",
        'unit_of_measurement': "VAR",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "q.2.q2consumecounter",
        'name': "Phase 2 reactive power consumption counter",
        'device_class': "energy",
        'unit_of_measurement': "kVAh",
        'state_class': "total_increasing",
        'suggested_display_precision': 2,
        'icon': "mdi:counter",
    },
    {
        'key': "q.2.q2supply",
        'name': "Phase 2 reactive power supply",
        'device_class': "reactive_power",
        'unit_of_measurement': "VAR",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "q.2.q2supplycounter",
        'name': "Phase 2 reactive power supply counter",
        'device_class': "energy",
        'unit_of_measurement': "kVAh",
        'state_class': "total_increasing",
        'suggested_display_precision': 2,
        'icon': "mdi:counter",
    },
    {
        'key': "s.2.s2consume",
        'name': "Phase 2 apparent power consumption",
        'device_class': "apparent_power",
        'unit_of_measurement': "VA",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "s.2.s2consumecounter",
        'name': "Phase 2 apparent power consumption counter",
        'device_class': "energy",
        'unit_of_measurement': "kVAh",
        'state_class': "total_increasing",
        'suggested_display_precision': 2,
        'icon': "mdi:counter",
    },
    {
        'key': "s.2.s2supply",
        'name': "Phase 2 apparent power supply",
        'device_class': "apparent_power",
        'unit_of_measurement': "VA",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "s.2.s2supplycounter",
        'name': "Phase 2 apparent power supply counter",
        'device_class': "energy",
        'unit_of_measurement': "kVAh",
        'state_class': "total_increasing",
        'suggested_display_precision': 2,
        'icon': "mdi:counter",
    },
    {
        'key': "2.i2",
        'name': "Phase 2 current",
        'device_class': "current",
        'unit_of_measurement': "A",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:current-ac",
    },
    {
        'key': "2.u2",
        'name': "Phase 2 potential",
        'device_class': "voltage",
        'unit_of_measurement': "V",
        'icon': "mdi:flash-triangle-outline",
        'state_class': "measurement",
        'suggested_display_precision': 2,
    },
    {
        'key': "2.cosphi2",
        'name': "Phase 2 angle cosine",
        'unit_of_measurement': "°",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:cosine-wave",
    },
    # phase 3 measurements
    {
        'key': "p.3.p3consume",
        'name': "Phase 3 consumption",
        'device_class': "power",
        'unit_of_measurement': "W",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "p.3.p3consumecounter",
        'name': "Phase 3 consumption counter",
        'device_class': "energy",
        'unit_of_measurement': "kWh",
        'state_class': "total_increasing",
        'suggested_display_precision': 2,
        'icon': "mdi:counter",
    },
    {
        'key': "p.3.p3supply",
        'name': "Phase 3 active power supply",
        'device_class': "power",
        'unit_of_measurement': "W",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "p.3.p3supplycounter",
        'name': "Phase 3 supply counter",
        'device_class': "energy",
        'unit_of_measurement': "kWh",
        'state_class': "total_increasing",
        'suggested_display_precision': 2,
        'icon': "mdi:counter",
    },
    {
        'key': "q.3.q3consume",
        'name': "Phase 3 reactive power consumption",
        'device_class': "reactive_power",
        'unit_of_measurement': "VAR",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "q.3.q3consumecounter",
        'name': "Phase 3 reactive power consumption counter",
        'device_class': "energy",
        'unit_of_measurement': "kVAh",
        'state_class': "total_increasing",
        'suggested_display_precision': 2,
        'icon': "mdi:counter",
    },
    {
        'key': "q.3.q3supply",
        'name': "Phase 3 reactive power supply",
        'device_class': "reactive_power",
        'unit_of_measurement': "VAR",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "q.3.q3supplycounter",
        'name': "Phase 3 reactive power supply counter",
        'device_class': "energy",
        'unit_of_measurement': "kVAh",
        'state_class': "total_increasing",
        'suggested_display_precision': 2,
        'icon': "mdi:counter",
    },
    {
        'key': "s.3.s3consume",
        'name': "Phase 3 apparent power consumption",
        'device_class': "apparent_power",
        'unit_of_measurement': "VA",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "s.3.s3consumecounter",
        'name': "Phase 3 apparent power consumption counter",
        'device_class': "energy",
        'unit_of_measurement': "kVAh",
        'state_class': "total_increasing",
        'suggested_display_precision': 2,
        'icon': "mdi:counter",
    },
    {
        'key': "s.3.s3supply",
        'name': "Phase 3 apparent power supply",
        'device_class': "apparent_power",
        'unit_of_measurement': "VA",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:home-lightning-bolt-outline",
    },
    {
        'key': "s.3.s3supplycounter",
        'name': "Phase 3 apparent power supply counter",
        'device_class': "energy",
        'unit_of_measurement': "kVAh",
        'state_class': "total_increasing",
        'suggested_display_precision': 2,
        'icon': "mdi:counter",
    },
    {
        'key': "3.i3",
        'name': "Phase 3 current",
        'device_class': "current",
        'unit_of_measurement': "A",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:current-ac",
    },
    {
        'key': "3.u3",
        'name': "Phase 3 potential",
        'device_class': "voltage",
        'unit_of_measurement': "V",
        'icon': "mdi:flash-triangle-outline",
        'state_class': "measurement",
        'suggested_display_precision': 2,
    },
    {
        'key': "3.cosphi3",
        'name': "Phase 3 angle cosine",
        'unit_of_measurement': "°",
        'state_class': "measurement",
        'suggested_display_precision': 2,
        'icon': "mdi:cosine-wave",
    },
]
